import Characters
def a(wpa):
  wpa=(wpa[0],wpa[1]+1)
  
def draw(wpa,wpb,wpc,wpd,wpe,wpf,wpg,wph,bpa,bpb,bpc,bpd,bpe,bpf,bpg,bph,wra,wrh,bra,brh,wq,bq,wk,bk,bng,bnb,wnb,wng,wbc,wbf,bbc,bbf):
  Characters.drawboard()

  Characters.pawn(wpa[0],wpa[1],"white")
  Characters.pawn(wpb[0],wpb[1],"white")
  Characters.pawn(wpc[0],wpc[1],"white")
  Characters.pawn(wpd[0],wpd[1],"white")
  Characters.pawn(wpe[0],wpe[1],"white")
  Characters.pawn(wpf[0],wpf[1],"white")
  Characters.pawn(wpg[0],wpg[1],"white")
  Characters.pawn(wph[0],wph[1],"white")
  Characters.rook(wra[0],wra[1],"white")
  Characters.rook(wrh[0],wrh[1],"white")
  Characters.queen(wq[0],wq[1],"white")
  Characters.king(wk[0],wk[1],"white")
  Characters.pawn(bpa[0],bpa[1],"black")
  Characters.pawn(bpb[0],bpb[1],"black")
  Characters.pawn(bpc[0],bpc[1],"black")
  Characters.pawn(bpd[0],bpd[1],"black")
  Characters.pawn(bpe[0],bpe[1],"black")
  Characters.pawn(bpf[0],bpf[1],"black")
  Characters.pawn(bpg[0],bpg[1],"black")
  Characters.pawn(bph[0],bph[1],"black")
  Characters.queen(wq[0],wq[1],"white")
  Characters.queen(bq[0],bq[1],"black")
  Characters.rook(bra[0],bra[1],"black")
  Characters.rook(brh[0],brh[1],"black")
  Characters.king(bk[0],bk[1],"black")
  Characters.knight(bng[0],bng[1],"black")
  Characters.knight(bnb[0],bnb[1],"black")
  Characters.knight(wnb[0],wnb[1],"white")
  Characters.knight(wng[0],wng[1],"white")
  Characters.bishop(wbc[0],wbc[1],"white")
  Characters.bishop(wbf[0],wbf[1],"white")
  Characters.bishop(bbc[0],bbc[1],"black")
  Characters.bishop(bbf[0],bbf[1],"black")